import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */
import * as enums from '../../enums';

export class TodoCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: enums.TodoStatusEnum;
  @ApiProperty()
  due_date: string;
}

export class Todo {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: enums.TodoStatusEnum;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
