/**
 * This file generated by Apso.
 */
import { TodoModule } from './Todo/Todo.module';
import { UserModule } from './User/User.module';
import { CommentModule } from './Comment/Comment.module';

export default [TodoModule, UserModule, CommentModule];
