/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Todo } from './Todo.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TodoService } from './Todo.service';
import { TodoController } from './Todo.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Todo])],
  providers: [TodoService],
  exports: [TodoService],
  controllers: [TodoController],
})
export class TodoModule {}
