import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class CommentCreate {
  @ApiProperty()
  todo_id: number;
  @ApiProperty()
  user_id: number;
  @ApiProperty()
  content: string;
  @ApiProperty()
  created_at: Date;
}

export class Comment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  todo_id: number;
  @ApiProperty()
  user_id: number;
  @ApiProperty()
  content: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
